extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "_"
      varsIgnorePattern: "_"
  "@typescript-eslint/no-var-requires":
    - warn
  "prefer-const":
      - warn
  "no-empty":
      - warn
